const express = require('express')
const {json,urlencoded} = require('express')
const auth = require('./middleware/auth')
const mongoose = require('mongoose')
mongoose.connect("mongodb://ravikiaran:qwerty12345@cluster0-shard-00-00.hzcsp.mongodb.net:27017,cluster0-shard-00-01.hzcsp.mongodb.net:27017,cluster0-shard-00-02.hzcsp.mongodb.net:27017/test?replicaSet=atlas-o8ir0s-shard-0&ssl=true&authSource=admin")
const userRouter = require("./routes/users")
const playlistRouter = require("./routes/playlist")
const musicRouter = require("./routes/music")
const app = express()
app.use(json())
app.use(urlencoded({extended:false}))
app.use(auth)
app.use('/users',userRouter)
app.use('/music',musicRouter)
app.use('/playlist',playlistRouter)
app.listen(5000)
